# Generated by Django 3.1.4 on 2021-01-23 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_calorie_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='calorieTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Calorie_Tracker',
        ),
    ]
